Ukol 5 Kaspar
TomasRacil/Ukoly2024 pull request #103
Opened 2024-11-20 08:01 UTC by schizo-coder-i-came-from-universe

2024-11-20 15:04 UTC, TomasRacil commented
Poprosím o provedení oprav v úkolu 1. Pátý úkol se zdá být v pořádku.

2024-12-11 18:54 UTC, schizo-coder-i-came-from-universe commented
Zdravím, snažil jsem se opravit co nejvíce checků, u většiny se mi to nakonec povedlo kromě úkolu 6 kde nevychazi JsouTahyRovny, ale přijde mi že program věže zobrazuje i počítá správně. S tím si bohužel nevím rady.

2024-12-12 13:42 UTC, TomasRacil requested changes

2024-12-12 13:42 UTC, TomasRacil commented on Ukol_6/cpp/hanoi.cpp
> +        provedTah(veze, tah);
```
provedTah(veze, tah);
tah.stavVezi = veze;
```

2024-12-12 13:42 UTC, TomasRacil commented on Ukol_6/cpp/hanoi.cpp
> +        provedTah(veze, tah);
```
provedTah(veze, tah);
tah.stavVezi = veze;
```

2025-01-22 08:04 UTC, TomasRacil approved these changes

2025-01-22 08:04 UTC, merged