ukol 2
TomasRacil/Ukoly2024 pull request #20
Opened 2024-10-20 19:24 UTC by johankak

2024-10-20 19:26 UTC, johankak commented
Nešlo mi propojit visual studio s Gitem a původně jsem psala kód zde v Gitu. Když jsem ho měla dopsaný, zkopírovala jsem ho a vložila do VS pro revizi a pak z VS zase zkopírovala a vložila sem. Snad to tak bude v pořádku

2024-10-21 05:11 UTC, TomasRacil commented
Dobrý den, podívám se na to, ale prvně vás poprosím o přesměrování vašeho pull requestu z main na vaši větev JohankaKarmazinova 

Díky

2024-10-30 16:11 UTC, TomasRacil requested changes
Je třeba opravit druhý úkol. (Ideálně i ostatní úkoly)

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_0/cpp/hello_world.cpp
> +    return "";
Zde chybí návratová hodnota.

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_0/python/hello_world.py
> +    return ""
Zde chybí návratová hodnota.

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +    }
Chybí vám uzavření bloku funkce.

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +
Chybí vám uzavření bloku funkce.

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +            znak = znak ^ klic[i % delka_klice];
`delka_klice` neni definovana

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +        int klic_delka = klic.lenght();
`klic.length()` nejspis nebude fungovat

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +    std::string xor_sifra(const std::string & text, const std::string & klic, bool sifrovat)
`std::` je zbytečné pokud jste použila `using namespace std`

2024-10-30 16:11 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +        os << current->data << " ";
Zde je to teměř v pořádku jen aby prošli testy nesmí byt mezera po každém znaku, ale pouze mezi nimi. Tedy "1 2 3" ne "1 2 3 "
Body za třetí úkol vám dám

2024-11-13 12:11 UTC, TomasRacil commented
Úkol 4 v pořádku ostatní poprosím opravit aby prošly testy

2024-11-20 12:58 UTC, merged