Ukol 2 Matej Tresnak
TomasRacil/Ukoly2024 pull request #23
Opened 2024-10-21 05:39 UTC by matejtresnak

2024-10-21 08:48 UTC, TomasRacil commented
Dobrý den, vytvořil jsem vám větev s vaším jménem prosím o přesunutí do této větve.

Dekuji

2024-10-30 16:23 UTC, TomasRacil requested changes
Poprosím o drobné úpravy body už máte zapsané

2024-10-30 16:23 UTC, TomasRacil commented on Ukol_0/cpp/hello_world.cpp
> +    return "";
Chybí návratová hodnota

2024-10-30 16:23 UTC, TomasRacil commented on Ukol_0/python/hello_world.py
> +    return ""
Chybí návratová hodnota

2024-10-30 16:23 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +    return result;
Výsledek šifrování pomocí XOR šifry mi nevachází správně. Slovo "Ahoj", zašifrované pomocí klíče "tajny" by mělo vracet řetězec "\025\t\005\004"

2024-10-30 16:23 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +        os << temp->data << " -> ";
Tady jen poprosím upravit ten tisk aby se tisknuli jen data např. "1 2 3"

2024-10-31 08:56 UTC, TomasRacil requested changes

2024-10-31 08:56 UTC, TomasRacil commented on Ukol_0/cpp/hello_world.cpp
> +    return "hello world";
Je třeba vracet "Hello world!" ne "hello world"

2024-10-31 08:56 UTC, TomasRacil commented on Ukol_0/python/hello_world.py
> +    return "hello world"
Je třeba vracet "Hello world!" ne "hello world"

2024-10-31 08:56 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +    return;
Váš kompilátor je schopný sestavit tento program? U mě tento řádek neakceptuje protože return musí mít nějakou hodnotu i kdyby to měl být prázdný string `return ""`

2024-10-31 08:56 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +        os << temp->data << " ";
téměř vyřešeno jen vám to na výstupu stále vrací ten nullptr "1 2 3 nullptr" místo pouze dat "1 2 3"

2024-11-01 10:19 UTC, TomasRacil requested changes

2024-11-01 10:19 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +    return result;
Tenhle problém stále přetrvává.

2024-11-01 10:19 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +        os << temp->data << " ";
Lepší ale stále je tam mezera na konci řetězce navíc.

2024-11-02 10:03 UTC, matejtresnak commented
Tu mezeru na konci výstupu v úkolu 3 jsem snad odstranil. XOR šifru v úkolu 2 už bohužel vůbec nevím jak opravit, takže pokud je to nutné, tak bych se na to zeptal někdy po hodině nebo na mentoringu.

2024-11-11 10:01 UTC, closed without merging