Ukol 2 - Jakub Vaclav Flasar
TomasRacil/Ukoly2024 pull request #25
Opened 2024-10-21 06:05 UTC by jakubvf

2024-10-21 08:45 UTC, TomasRacil requested changes
U viegnerovy šifry test neprošel teď jsem na střelbách tak nemůžu ověřit jestli je špatný test nebo vaše řešení můžete se na to kouknout a dát mi vědět.

2024-10-21 11:46 UTC, jakubvf commented
Nejspíš test.

```
[ RUN      ] SifrovaciAlgoritmyTest.VigenerSifra
/Users/jvf/dev/unbo/Ukoly2024/Ukol_2/cpp/test.cpp:35: Failure
Expected equality of these values:
  vigener_sifra(text, "tajny", true)
    Which is: "thxw"
  "kftm"
```


Mám stejný výsledek jako v online aplikaci:
<img width="815" alt="Screenshot 2024-10-21 at 13 45 38" src="https://github.com/user-attachments/assets/19b9e524-5f14-4c87-b6f2-daac1844418f">

2024-10-21 11:48 UTC, jakubvf commented
Stejný případ u XORu:
```
/Users/jvf/dev/unbo/Ukoly2024/Ukol_2/cpp/test.cpp:49: Failure
Expected equality of these values:
  xor_sifra(text, "tajny", true)
    Which is: "\x15\t\x5\x4"
  "\x06\x1d\x1a\x0b"
    Which is: "\x6\x1D\x1A\v"
```

<img width="816" alt="Screenshot 2024-10-21 at 13 47 53" src="https://github.com/user-attachments/assets/9be6a7ec-6ff2-42e1-83b3-ccc83b9eb7d8">

2024-10-22 07:48 UTC, TomasRacil approved these changes
Teď už vše v pořádku jen bych vás poprosil o doplnění prvního úkolu v příštím pull requestu.

2024-10-22 07:48 UTC, merged