Ukol_2_szaffner
TomasRacil/Ukoly2024 pull request #26
Opened 2024-10-21 06:28 UTC by otakarszaffner

2024-10-21 08:48 UTC, TomasRacil commented
Dobrý den, vytvořil jsem vám větev s vaším jménem prosím o přesunutí do této větve.

Dekuji

2024-10-23 17:09 UTC, TomasRacil requested changes
Prosím o opravu toho jednoho řádku body jsem vám již zapsal

2024-10-23 17:09 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> +    exit(1);
poprosím vás tento radek nahradit return "" testy jsou napsane tak ze pokud soubor nexistuje měla by funkce vratit prazdny retezec

2024-10-30 16:39 UTC, TomasRacil requested changes
Poprosím o opravu a doplnění Úkolu 1

2024-10-30 16:39 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +}
Tato funkce by měla mít návratovou hodnotu.

2024-10-30 16:39 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +void insertAtIndex(Node **head, int data, int index)
Tato funkce nefunguje správně pokud chceme vložit hodnotu na 0 index tedy na začátek linked listu.

2024-11-01 10:27 UTC, TomasRacil requested changes
U úkolu dva jsou stále chyby u viegnera a caesara + to co jsem označil

2024-11-01 10:27 UTC, TomasRacil commented on Ukol_1/python/vypocty.py
> +  return prum
nefunguje správně pokud je předán prázdný seznam.

2024-11-01 10:27 UTC, TomasRacil commented on Ukol_1/python/vypocty.py
> +  return soucin
nefunguje správně pokud je předán prázdný seznam.

2024-11-01 10:27 UTC, TomasRacil commented on Ukol_1/python/vypocty.py
> +    return cisla[delka//2]
nefunguje správně pokud je předán prázdný seznam.

2024-11-13 11:53 UTC, TomasRacil requested changes
Poprosím o opravy tak aby testy proběhly v pořádku.

2024-11-13 11:53 UTC, TomasRacil commented on Ukol_4/cpp/advent_lod.cpp
Tento úkol není vyřešen.

2024-11-13 11:53 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
Stále nefunguje správně.

2024-11-20 14:46 UTC, TomasRacil requested changes
U úkolu jedna vám chybí řešení v cpp a python má stále drobné chyby podívejte se na výsledky testů.

2024-11-20 14:46 UTC, TomasRacil commented on Ukol_5/cpp/source.cpp
tenhle main vám asi simulaci prostředí nepustí

2024-11-26 11:21 UTC, TomasRacil commented
Poprosím jen o opravu úkolu 1 v pythonu ať mohu tento pull request uzavřít.

2024-11-26 13:10 UTC, otakarszaffner commented
nevim proc mi nefunguje test u ukolu 1 stale, kdyz si to pustim u sebe a zadam stejny vstup tak to funguje

2024-11-27 11:04 UTC, TomasRacil requested changes
Tohle je třeba opravit pak by to snad mělo být dobře

2025-03-03 12:22 UTC, TomasRacil requested changes
Vše v pořádku až na uvedené.

2025-03-03 12:22 UTC, TomasRacil commented on Ukol_1/cpp/test.cpp
Test měl projít tak jak byly testy napsány neměl jste si je upravovat.

2025-03-07 10:45 UTC, TomasRacil reviewed
Vše ok.

2025-03-07 10:46 UTC, merged