Ukol2 - Linek
TomasRacil/Ukoly2024 pull request #38
Opened 2024-10-22 18:43 UTC by Czert1892

2024-10-23 17:37 UTC, TomasRacil commented
Nejake body vam zapisu, ale predelejte to do takového formátu aby na tom bylo mozne provozovat testy. Je treba zajistit že funkce maji stejne nazvy parametry a vystup a take

2024-10-23 17:38 UTC, TomasRacil requested changes

2024-10-23 17:38 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> -#ifndef __TEST__ // Add this preprocessor guard
Tohle je třeba zachovat

2024-10-23 17:38 UTC, TomasRacil commented on Ukol_2/cpp/sifry.cpp
> -#endif // __TEST__
Tohle také

2024-10-23 17:38 UTC, TomasRacil commented on Ukol_2/cpp/sifry_done.cpp
Nebo nejspis staci prejmenovat tento soubor na sifry a druhy na cokoliv jineho

2024-10-30 16:43 UTC, TomasRacil commented
Stále jste neopravil výše uvedené prosím o opravu.

2024-11-13 12:15 UTC, TomasRacil commented
Úkol 4 poprosím doplnit i sem ale body jsem vám zapsal + opravit všechny úkoly, tak aby prošly všechny testy

2025-01-24 10:32 UTC, TomasRacil requested changes
Podívejte se na tyto dvě věci pak by jste to měl mít v pořádku

2025-01-24 10:32 UTC, TomasRacil commented on Ukol_7/python/matice.py
> +        return None
Test očekává že tady budete vracet [] ne None
matice1 = [[1, 2], [3, 4]]
nasobeni_matic(matice1, [])

2025-01-24 10:32 UTC, TomasRacil commented on Ukol_9/python/SystemKnihovny/Knihovna.py
> +                if row['typ'] == 'kniha':
Tato část je špatně. Musíte prvně přečíst první řádek aby jste z csv souboru odebral název knihovny a až pak pracovat s knihami 

test_z_csv (test.TestKnihovna)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Ukoly2024/Ukoly2024/Ukol_[9](https://github.com/TomasRacil/Ukoly2024/actions/runs/12732765525/job/35488330998?pr=38#step:4:10)/python/test.py", line 45, in test_z_csv
    knihovna = Knihovna.z_csv("test_knihovna.csv")
  File "/home/runner/work/Ukoly2024/Ukoly2024/Ukol_9/python/SystemKnihovny/Knihovna.py", line 44, in z_csv
    if row['typ'] == 'kniha':
KeyError: 'typ'

2025-01-25 16:46 UTC, Czert1892 commented
Dobrý den, děkuji za rady, snad by mělo být už vše v pořádku. Kdyby mi sházely nějaké body, prosím, dejte vědět, rád bych si to opravil ještě aby mi ty body potom nechyběly. Děkuji, Línek

2025-01-27 08:38 UTC, TomasRacil approved these changes

2025-01-27 08:40 UTC, merged