Ukol2_Daniel_Bilek
TomasRacil/Ukoly2024 pull request #50
Opened 2024-10-23 15:21 UTC by DanielBi1ek

Omylem jsem si smazal reopositář a tím všechny pullrequesty tak je tu dávám znovu.

2024-10-23 18:18 UTC, TomasRacil requested changes

2024-10-23 18:18 UTC, TomasRacil commented on Ukol_0/cpp/hello_world.cpp
> +    return "";
Vyřešte prosím i tuto funkci

2024-10-23 18:18 UTC, TomasRacil commented on Ukol_0/python/hello_world.py
> +    return ""
Vyřešte prosím i tuto funkci

2024-10-23 18:18 UTC, TomasRacil commented on Ukol_1/cpp/vypocty.cpp
>  int soucin(const std::vector<int> &cisla)
U soucinu prazdneho seznamu dostavam hodnotu 1 ale očekával bych spíš 0

2024-10-23 18:18 UTC, TomasRacil commented on Ukol_1/cpp/vypocty.cpp
>  double prumer(const std::vector<int> &cisla)
Pokud pošlu do funkce prazdny seznam dostanu chybu division by zero treba osetrit

2024-10-23 18:18 UTC, TomasRacil commented on Ukol_1/cpp/vypocty.cpp
>  double median(const std::vector<int> &cisla)
median mi u prazdneho seznamu vraci list index out of range treba osetrit

2024-10-24 19:16 UTC, DanielBi1ek commented
Ukol 0 jsem doplnil, a chyby v ukolu 1 jsem ošetřil.

2024-10-30 17:05 UTC, TomasRacil requested changes
Poprosím o opravu body za třetí úkol vám zapíšu

2024-10-30 17:05 UTC, TomasRacil commented on Ukol_1/python/vypocty.py
> +        return (cisla[delka // 2 - 1] + cisla[delka // 2]) / 2
Tady dostávám list out of range error pokud přidám prázdný list poprosím o kontrolu prázdného listu a následně zavolání `raise ValueError`

2024-10-30 17:05 UTC, TomasRacil commented on Ukol_1/python/vypocty.py
> +    return sum(cisla) / len(cisla)
Pokud předám prázdný list prosím o `raise ValueError`

2024-10-30 17:05 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +        os << temp->data << " "; // Vytiskne hodnotu uzlu
Zde prosím o opravu přebytečných mezer. Výstupem má být například "1 2 3" ne "1 2 3 "

2024-10-31 16:33 UTC, DanielBi1ek commented on Ukol_3/cpp/linked_list.cpp
> +        os << temp->data << " "; // Vytiskne hodnotu uzlu
Opraveno

2024-10-31 16:54 UTC, DanielBi1ek commented
Všechny chyby by měly být odstraněny

2024-11-20 15:22 UTC, TomasRacil commented
Vše vypadá v pořádku. Pátý úkol jsem vám zapsal.

2024-11-20 15:23 UTC, merged