ukol3
TomasRacil/Ukoly2024 pull request #63
Opened 2024-10-29 12:59 UTC by SickSkater

Dobrý den posílám úkol 3 - Vojtěch Valiašek

2024-10-30 17:48 UTC, TomasRacil commented
Poprosím vás o informaci o vašem jméně a příjmení. Jinak vám nemůžu vytvořit váš branch.

2024-11-01 09:11 UTC, TomasRacil requested changes

2024-11-01 09:11 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +void deleteAtBeginning(Node** head)
U této funkce selhává volání vrací Segmentation fault
```
Node *head = nullptr;
insertAtEnd(&head, 1);
insertAtEnd(&head, 2);
deleteAtEnd(&head);
```

2024-11-01 09:11 UTC, TomasRacil commented on Ukol_3/cpp/linked_list.cpp
> +        os << rem->data;
Tady vám chybí mezery mezi jednotlivými hodnotami "123" správně "1 2 3"

2024-11-13 12:01 UTC, TomasRacil commented
Úkol 4 nefunguje správně a poprosím taky o opravu všeho co neprošlo testy

2024-11-26 10:27 UTC, TomasRacil commented
Zkuste opravit úkoly, které neprošly testy. U úkolu šest vám také všechny testy neprošly, tak se na to koukněte, ale body jsem vám zapsal.

2024-11-26 11:32 UTC, SickSkater reviewed
Oprava a doplnění úkolů

2024-11-26 11:41 UTC, SickSkater commented
oprava úkolů krom 6. doplnění 0/1/2 z cizího zdroje, vlastní řešení byla odevzdána na email po dohodě. Úkol 6 nehází chybu na VS, poprosím o pomoc s vyřešením segmentační chyby

2024-11-27 07:19 UTC, SickSkater commented
oprava úkolů, zkopírování úkolů 0/1/2 pro odstranění varování, vlastní úkoly 1,2 odevzdány na email. úkol 6 a 5 oprava chyb

2024-11-27 10:55 UTC, TomasRacil commented
Super, děkuji za odevzdání a opravu.

2024-11-27 10:56 UTC, merged